stages:
    - build
    - test
    - deploy

build website:
    stage: build
    image: node:16.14.2-bullseye
    script:
        - npm install
        - npm install -g gatsby-cli
        - gatsby build
    artifacts:
        when: always
        paths:
            - ./public

test artifacts:
    stage: test
    image: alpine
    script:
        - grep -i "gatsby" ./public/index.html

test website:
    stage: test
    image: node:16.14.2-bullseye
    script: 
        - npm install
        - npm install -g gatsby-cli
        - gatsby serve -p 9001 &
        - sleep 5
        - curl "http://localhost:9001" | grep -iq "gatsby"

deploy to surge:
    stage: deploy
    script:
        - npm install -g surge
        - surge --project ./public --domain grubby-desire.surge.sh 
